Repository lf-lang/lf-lang.github.io, pull requests merged in 2024-01, with the labels that each got.

#214 Added pointer to RP2040 docs
  docs/embedded/rp2040.mdx
  docs/sidebars.ts
Labels: documentation

#217 Added a page showing how to debug generated code
  docs/assets/images/debugging/cmake-debug.png
  docs/assets/images/debugging/cmake-tools.png
  docs/assets/images/debugging/wrong-debug.png
  docs/developer/debugging-generated-code.mdx
  docs/sidebars.ts
Labels: documentation

#224 Changes regarding `single-threaded` target property
  docs/reference/target-declaration.mdx
Labels: v0.6.0

#220 Improved Zephyr docs
  docs/embedded/zephyr.mdx
Labels: documentation, enhancement
